# This test is for develop←branch , and test←develop or test←branch pull requests.
# It runs on Ubuntu, and tests Python 3.11. For testing for production, see /.github/workflows/python-package-release.yml

name: Test Python package on Ubuntu

on:
  pull_request:
    branches: [test, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Create virtual environment
        run: python -m venv my_env
      - name: Install dependencies
        run: |
          source my_env/bin/activate
          pip install .[test]
      #- name: Lint with flake8
      #  run: |
      #    source my_env/bin/activate
      #    # stop the build if there are Python syntax errors or undefined names
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          # Options: --ignore=tests/specific.py --ignore-glob=tests/ignore-pattern
          source my_env/bin/activate
          pytest ./tests/unit/
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
      - name: Compress virtual environment
        run: |
          tar -czvf my_env.tar.gz my_env
          mv my_env.tar.gz my_env
      - name: Upload virtual environment as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_env
          path: my_env/my_env.tar.gz