# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Package documentation - check build

on:
  push:
    branches: [ main, dev, test, prod, develop, release ]
  pull_request:
    branches: [ main, dev, test, prod, develop, release ]

jobs:
  build:

    runs-on: ubuntu-latest  # Alternative: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install -r docs/requirements.txt

    - name: Test jupyterbook build of documentation
      run: |
        ls -R 
        # copied contents of build.sh
        python docs/build_md.py
        python docs/build_jpb.py

        cd ./docs/build/
        jupyter-book build macrosynergy
        jupyter-book config sphinx macrosynergy

        cd ../..

        python docs/post_build.py

