# Unit tests for the package, running on PRs to `test` and `develop` branches
name: Test Python package on Ubuntu

on:
  pull_request:
    branches: [test, develop]
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore caches - Python 3.11
        uses: ./.github/actions/restore-pip-cache
        with:
          python-version: 3.11

      - name: Check for sys.path.append
        run: |
          find . -type f ! -name '*.yml' -exec grep -H "sys\.path\.append(os\.getcwd())" {} \;
          if [ $? -eq 0 ]; then
            echo "ERROR: Found 'sys.path.append(os.getcwd())' in the following file(s):"
            find . -type f ! -name '*.yml' -exec grep -H "sys\.path\.append(os\.getcwd())" {} \; | cut -d':' -f1 | sort -u
            exit 1
          fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          # Options: --ignore=tests/specific.py --ignore-glob=tests/ignore-pattern
          python -m pytest ./tests/unit/
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
