# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Integration tests

on:
  pull_request:
    branches: [main, test, develop]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
            
      - name: Install dependencies
        run: |
          pip install pytest>=7.0.1 pytest-cov>3.0.0 coverage>=6.0.0 pytest-xdist>=3.3.1 flake8>=4.0.1

      - name: Run integration tests with pytest
        env:
          DQ_CLIENT_ID: ${{ secrets.DQ_CLIENT_ID }}
          DQ_CLIENT_SECRET: ${{ secrets.DQ_CLIENT_SECRET }}
        run: |
          echo 'Run Integration tests'
          pytest tests/integration/
          echo 'Integration test complete'

      - name: Test build settings
        run: |
          pip install .[all] 
          python -c "import macrosynergy; print(macrosynergy.__version__)"
