name: Package documentation - check build

on:
  pull_request:
    branches: [main, test, develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          pip install flake8
          pip install -r docs/requirements.txt

      - name: Zip Package
        run: |
          zip -r package.zip . -x ".git/*"

      - name: Cache Package
        uses: actions/cache@v2
        with:
          path: package.zip
          key: ${{ runner.os }}-package-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-package-
      
      - name: Unzip Package
        run: unzip package.zip -d extracted_package

      - name: Build docs
        run: |
          bash docs/scripts/build.sh

