# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Integration tests

on:
  pull_request:
    branches: [main, test, develop]
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cache
        run: |
          echo "::set-output name=cache::false"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python packages
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - if: ${{ steps.pip-cache.outputs.cache-hit != 'true' }}
        run: |
          pip install .[test]

      - name: Run integration tests with pytest
        env:
          DQ_CLIENT_ID: ${{ secrets.DQ_CLIENT_ID }}
          DQ_CLIENT_SECRET: ${{ secrets.DQ_CLIENT_SECRET }}
        run: |
          echo 'Run Integration tests'
          pytest tests/integration/
          echo 'Integration test complete'

      - name: Test build settings
        run: |
          pip install .[all] 
          python -c "import macrosynergy; print(macrosynergy.__version__)"